// questions.js
// level: E = Dễ, M = Trung bình, H = Khó
window.QUESTION_BANK = [
  // ===================== 60 CÂU DỄ (E01–E60) =====================
  {
    id: "E01",
    level: "E",
    q: "Khi có dông sét, nơi trú an toàn hơn là:",
    A: "Dưới gốc cây to",
    B: "Trong nhà kiên cố",
    C: "Gần cột điện",
    D: "Trên sân thượng",
    ans: "B",
  },
  {
    id: "E02",
    level: "E",
    q: "Vật nên có trong “túi khẩn cấp” là:",
    A: "Đèn pin",
    B: "Pháo giấy",
    C: "Nước ngọt có gas",
    D: "Loa lớn",
    ans: "A",
  },
  {
    id: "E03",
    level: "E",
    q: "Khi có cảnh báo bão mạnh, việc nên làm đầu tiên:",
    A: "Ra biển xem sóng",
    B: "Theo dõi thông báo chính quyền",
    C: "Đi tắm mưa",
    D: "Leo lên mái nhà",
    ans: "B",
  },
  {
    id: "E04",
    level: "E",
    q: "Trong lũ, điều nguy hiểm nhất khi đi bộ qua dòng nước là:",
    A: "Nước mát",
    B: "Bị cuốn trôi",
    C: "Giày ướt",
    D: "Bẩn quần áo",
    ans: "B",
  },
  {
    id: "E05",
    level: "E",
    q: "Gặp dây điện bị đứt sau mưa bão, bạn nên:",
    A: "Chạm thử xem còn điện không",
    B: "Đứng xa và báo người lớn/điện lực",
    C: "Nhặt lên cất đi",
    D: "Rải nước lên cho mát",
    ans: "B",
  },
  {
    id: "E06",
    level: "E",
    q: "Việc giúp giảm rác nhựa là:",
    A: "Dùng túi nilon 1 lần",
    B: "Mang bình nước cá nhân",
    C: "Vứt rác xuống kênh",
    D: "Đốt nhựa ngoài trời",
    ans: "B",
  },
  {
    id: "E07",
    level: "E",
    q: "Khi nắng nóng kéo dài, cách tốt để bảo vệ sức khỏe:",
    A: "Uống ít nước cho đỡ đi vệ sinh",
    B: "Uống đủ nước và nghỉ nơi mát",
    C: "Chơi thể thao giữa trưa",
    D: "Mặc áo dày hơn",
    ans: "B",
  },
  {
    id: "E08",
    level: "E",
    q: "Bão thường kèm theo:",
    A: "Gió mạnh, mưa lớn",
    B: "Tuyết rơi",
    C: "Động đất",
    D: "Núi lửa",
    ans: "A",
  },
  {
    id: "E09",
    level: "E",
    q: "Để tiết kiệm điện, nên:",
    A: "Bật điều hòa 16°C cả ngày",
    B: "Tắt thiết bị khi không dùng",
    C: "Mở tủ lạnh lâu cho mát",
    D: "Bật đèn mọi phòng",
    ans: "B",
  },
  {
    id: "E10",
    level: "E",
    q: "Khi nghe còi/loa sơ tán, bạn cần:",
    A: "Tranh thủ quay video",
    B: "Đi theo hướng dẫn sơ tán",
    C: "Chạy tán loạn mỗi người một hướng",
    D: "Ở lại vì “chắc không sao”",
    ans: "B",
  },
  {
    id: "E11",
    level: "E",
    q: "Nếu thấy nước dâng nhanh bất thường, nên:",
    A: "Ở lại tầng trệt",
    B: "Di chuyển lên nơi cao và báo người lớn",
    C: "Ra ngoài nghịch nước",
    D: "Mở cửa cho nước vào",
    ans: "B",
  },
  {
    id: "E12",
    level: "E",
    q: "Hành động “sống xanh” là:",
    A: "Trồng cây",
    B: "Đốt rơm rạ nhiều khói",
    C: "Xả rác bừa",
    D: "Chạy xe nổ máy đứng yên lâu",
    ans: "A",
  },
  {
    id: "E13",
    level: "E",
    q: "Khi có sạt lở đất, dấu hiệu có thể là:",
    A: "Đất nứt, đá rơi",
    B: "Trời xanh",
    C: "Gió nhẹ",
    D: "Nắng đẹp",
    ans: "A",
  },
  {
    id: "E14",
    level: "E",
    q: "Khi đi học gặp mưa lớn ngập đường, nên:",
    A: "Lội qua chỗ sâu",
    B: "Tìm đường an toàn/nhờ người lớn",
    C: "Đua xe qua nước",
    D: "Tạt nước vào bạn",
    ans: "B",
  },
  {
    id: "E15",
    level: "E",
    q: "Khi cháy trong nhà, việc nên làm:",
    A: "Núp trong phòng kín",
    B: "Báo người lớn, gọi cứu hỏa và thoát ra",
    C: "Mở toang cửa cho gió thổi mạnh",
    D: "Trốn dưới giường",
    ans: "B",
  },
  {
    id: "E16",
    level: "E",
    q: "Nước biển dâng có thể làm:",
    A: "Tăng đất liền",
    B: "Ngập vùng ven biển",
    C: "Giảm mưa",
    D: "Giảm sóng",
    ans: "B",
  },
  {
    id: "E17",
    level: "E",
    q: "Cách giảm khí thải đơn giản:",
    A: "Đi bộ/xe đạp khi có thể",
    B: "Đốt rác mỗi tối",
    C: "Bật xe nổ máy chờ lâu",
    D: "Mở máy lạnh khi không cần",
    ans: "A",
  },
  {
    id: "E18",
    level: "E",
    q: "Khi có tin bão giả trên mạng, bạn nên:",
    A: "Share ngay cho nóng",
    B: "Kiểm tra nguồn chính thống",
    C: "Chửi nhau trong bình luận",
    D: "Tự bịa thêm",
    ans: "B",
  },
  {
    id: "E19",
    level: "E",
    q: "Số điện thoại khẩn cấp phổ biến ở VN để gọi cứu hỏa:",
    A: "113",
    B: "114",
    C: "115",
    D: "111",
    ans: "B",
  },
  {
    id: "E20",
    level: "E",
    q: "Số điện thoại để gọi cấp cứu:",
    A: "115",
    B: "114",
    C: "113",
    D: "112",
    ans: "A",
  },
  {
    id: "E21",
    level: "E",
    q: "Một cách tránh sốc nhiệt:",
    A: "Ở ngoài nắng lâu cho quen",
    B: "Đội nón, nghỉ mát, uống nước",
    C: "Uống rượu cho mát",
    D: "Mặc áo khoác dày",
    ans: "B",
  },
  {
    id: "E22",
    level: "E",
    q: "Khi dông sét, không nên:",
    A: "Rút phích thiết bị khi cần",
    B: "Cầm vật kim loại ngoài trời",
    C: "Ở trong nhà",
    D: "Đóng cửa sổ",
    ans: "B",
  },
  {
    id: "E23",
    level: "E",
    q: "Đồ ăn dự trữ trong bão nên là:",
    A: "Thức ăn dễ hư để ngoài",
    B: "Đồ khô/đóng hộp",
    C: "Kem",
    D: "Đồ sống không bảo quản",
    ans: "B",
  },
  {
    id: "E24",
    level: "E",
    q: "Khi lũ, nước chảy xiết, bạn nên:",
    A: "Bơi thi",
    B: "Không xuống nước",
    C: "Chơi thả thuyền giấy sát miệng cống",
    D: "Đứng sát bờ kè trơn",
    ans: "B",
  },
  {
    id: "E25",
    level: "E",
    q: "Biến đổi khí hậu liên quan đến:",
    A: "Trái Đất ấm lên",
    B: "Mặt Trăng đổi màu",
    C: "Sao Hỏa gần hơn",
    D: "Cầu vồng nhiều",
    ans: "A",
  },
  {
    id: "E26",
    level: "E",
    q: "Rác hữu cơ (thức ăn thừa) tốt nhất là:",
    A: "Đổ xuống sông",
    B: "Phân loại để ủ/đổ đúng nơi",
    C: "Đốt trong phòng",
    D: "Vứt lẫn pin",
    ans: "B",
  },
  {
    id: "E27",
    level: "E",
    q: "Trong mưa bão, nơi nguy hiểm là:",
    A: "Trong nhà kiên cố",
    B: "Dưới biển quảng cáo, cây to",
    C: "Phòng học chắc chắn",
    D: "Nhà văn hóa",
    ans: "B",
  },
  {
    id: "E28",
    level: "E",
    q: "Khi thấy người bị điện giật, bạn cần:",
    A: "Chạm kéo người ngay",
    B: "Ngắt nguồn điện/ gọi người lớn",
    C: "Đổ nước vào",
    D: "Đứng nhìn",
    ans: "B",
  },
  {
    id: "E29",
    level: "E",
    q: "Để giảm ngập, việc hữu ích:",
    A: "Vứt rác vào cống",
    B: "Giữ cống rãnh thông thoáng",
    C: "Bịt miệng cống",
    D: "Đổ dầu xuống cống",
    ans: "B",
  },
  {
    id: "E30",
    level: "E",
    q: "Khi có cảnh báo triều cường, nên:",
    A: "Để xe thấp sát nước",
    B: "Kê đồ lên cao, che chắn cửa",
    C: "Mở cửa cho nước vào",
    D: "Ra bờ sông chơi",
    ans: "B",
  },
  {
    id: "E31",
    level: "E",
    q: "Hiện tượng “nắng nóng gay gắt” dễ gây:",
    A: "Sốc nhiệt",
    B: "Lạnh run",
    C: "Tuyết",
    D: "Mọc rêu",
    ans: "A",
  },
  {
    id: "E32",
    level: "E",
    q: "Một hành vi tiết kiệm nước:",
    A: "Mở vòi xả liên tục",
    B: "Tắt vòi khi đang đánh răng",
    C: "Rửa sân bằng vòi mạnh lâu",
    D: "Đổ nước sạch đi",
    ans: "B",
  },
  {
    id: "E33",
    level: "E",
    q: "Khi đi thuyền/đò mùa mưa lũ, nên:",
    A: "Không cần áo phao",
    B: "Mặc áo phao đúng cách",
    C: "Đứng nhảy trên thuyền",
    D: "Chạy qua lại",
    ans: "B",
  },
  {
    id: "E34",
    level: "E",
    q: "Nếu nhà ở vùng hay ngập, nên chuẩn bị:",
    A: "Ổ cắm thấp sát sàn",
    B: "Kê đồ và giấy tờ quan trọng lên cao",
    C: "Để giấy tờ ngoài hiên",
    D: "Chất đồ nặng trước cửa thoát",
    ans: "B",
  },
  {
    id: "E35",
    level: "E",
    q: "Để giảm ô nhiễm không khí, nên:",
    A: "Đốt rác nhựa",
    B: "Trồng cây, hạn chế đốt",
    C: "Đốt than trong phòng kín",
    D: "Xả khói nhiều",
    ans: "B",
  },
  {
    id: "E36",
    level: "E",
    q: "Khi gió giật mạnh, bạn nên tránh:",
    A: "Kính cửa sổ",
    B: "Đứng gần cửa kính/ban công",
    C: "Ngồi trong phòng chắc",
    D: "Nghe hướng dẫn",
    ans: "B",
  },
  {
    id: "E37",
    level: "E",
    q: "Bão đến, điều cần làm với cửa sổ:",
    A: "Mở hết cho thoáng",
    B: "Đóng và gia cố",
    C: "Tháo ra",
    D: "Đập kính",
    ans: "B",
  },
  {
    id: "E38",
    level: "E",
    q: "Khi có nguy cơ lũ quét, nên:",
    A: "Cắm trại ven suối",
    B: "Tránh xa sông suối, di chuyển sớm",
    C: "Đi bắt cá",
    D: "Chơi đá ven dòng",
    ans: "B",
  },
  {
    id: "E39",
    level: "E",
    q: "Điều giúp giảm hiệu ứng nhà kính:",
    A: "Giảm dùng điện không cần thiết",
    B: "Bật nhiều máy lạnh",
    C: "Đốt xăng nhiều hơn",
    D: "Chặt cây",
    ans: "A",
  },
  {
    id: "E40",
    level: "E",
    q: "Khi thiếu nước do hạn hán, nên:",
    A: "Xả nước thoải mái",
    B: "Ưu tiên nước cho uống và sinh hoạt thiết yếu",
    C: "Rửa xe mỗi ngày",
    D: "Tưới sân cả giờ",
    ans: "B",
  },
  {
    id: "E41",
    level: "E",
    q: "Khi nghe dự báo thời tiết, thông tin quan trọng là:",
    A: "Tên MC",
    B: "Cấp gió, lượng mưa, khu vực ảnh hưởng",
    C: "Nhạc nền",
    D: "Quảng cáo",
    ans: "B",
  },
  {
    id: "E42",
    level: "E",
    q: "Một cách an toàn khi bão là:",
    A: "Ra đường chụp ảnh",
    B: "Ở trong nhà, tránh ra ngoài",
    C: "Đứng trên cầu ngắm nước",
    D: "Tắm mưa",
    ans: "B",
  },
  {
    id: "E43",
    level: "E",
    q: "Mưa lớn kéo dài có thể gây:",
    A: "Sạt lở",
    B: "Tăng nắng",
    C: "Giảm nước",
    D: "Tạo tuyết",
    ans: "A",
  },
  {
    id: "E44",
    level: "E",
    q: "Để giảm nguy cơ dịch bệnh sau lũ:",
    A: "Uống nước bẩn",
    B: "Rửa tay, dùng nước sạch, vệ sinh môi trường",
    C: "Ăn đồ sống",
    D: "Không dọn dẹp",
    ans: "B",
  },
  {
    id: "E45",
    level: "E",
    q: "Trong nhà, vật nguy hiểm khi gió mạnh:",
    A: "Đồ nhẹ bay được (chậu, tôn)",
    B: "Gạch nặng nằm yên",
    C: "Bàn cố định",
    D: "Tường",
    ans: "A",
  },
  {
    id: "E46",
    level: "E",
    q: "Pin đã dùng nên:",
    A: "Vứt chung rác thường",
    B: "Bỏ đúng điểm thu gom pin",
    C: "Ném xuống ao",
    D: "Đốt",
    ans: "B",
  },
  {
    id: "E47",
    level: "E",
    q: "Khi trời rét đậm, nên:",
    A: "Tắm khuya nước lạnh",
    B: "Giữ ấm và ăn uống đủ chất",
    C: "Mặc mỏng",
    D: "Ngồi gió lùa",
    ans: "B",
  },
  {
    id: "E48",
    level: "E",
    q: "Vì sao không nên trú mưa dưới gốc cây khi dông?",
    A: "Vì cây dễ bị sét đánh",
    B: "Vì cây không đẹp",
    C: "Vì trời tối",
    D: "Vì mưa nhỏ",
    ans: "A",
  },
  {
    id: "E49",
    level: "E",
    q: "Nếu thấy mùi gas trong nhà:",
    A: "Bật công tắc điện kiểm tra",
    B: "Mở cửa thông gió, khóa van, báo người lớn",
    C: "Đốt bật lửa",
    D: "Dùng quạt thổi sát bếp",
    ans: "B",
  },
  {
    id: "E50",
    level: "E",
    q: "Khi sơ tán, điều quan trọng là:",
    A: "Mang thật nhiều đồ chơi",
    B: "Mang giấy tờ, thuốc, nước và theo nhóm",
    C: "Đi một mình nhanh cho tiện",
    D: "Quay lại lấy mọi thứ",
    ans: "B",
  },
  {
    id: "E51",
    level: "E",
    q: "Rừng giúp giảm thiên tai vì:",
    A: "Giữ đất, giảm sạt lở",
    B: "Làm trời nóng hơn",
    C: "Tạo bão",
    D: "Làm nước biển dâng",
    ans: "A",
  },
  {
    id: "E52",
    level: "E",
    q: "Trong ngập, chỗ nguy hiểm nhất:",
    A: "Nước tĩnh nông",
    B: "Miệng cống/hố ga",
    C: "Nơi có lan can",
    D: "Chỗ có đèn",
    ans: "B",
  },
  {
    id: "E53",
    level: "E",
    q: "Một thói quen tốt để giảm phát thải:",
    A: "Tắt đèn khi ra khỏi phòng",
    B: "Bật đèn cả ngày",
    C: "Mở TV khi ngủ",
    D: "Sạc pin liên tục",
    ans: "A",
  },
  {
    id: "E54",
    level: "E",
    q: "Khi gió lớn, vật nào dễ bay nguy hiểm:",
    A: "Tấm tôn, bảng quảng cáo",
    B: "Cục đá",
    C: "Nền nhà",
    D: "Bức tường",
    ans: "A",
  },
  {
    id: "E55",
    level: "E",
    q: "Sạt lở ven sông thường tăng khi:",
    A: "Không mưa",
    B: "Mưa lớn + dòng chảy mạnh",
    C: "Trời lạnh",
    D: "Trời quang",
    ans: "B",
  },
  {
    id: "E56",
    level: "E",
    q: "Để an toàn khi sét, trong nhà nên tránh:",
    A: "Đứng gần cửa kính",
    B: "Ngồi giữa phòng",
    C: "Nghe radio pin",
    D: "Ở xa cửa sổ",
    ans: "A",
  },
  {
    id: "E57",
    level: "E",
    q: "Biện pháp giảm rác ở trường:",
    A: "Mỗi ngày dùng 3 ly nhựa",
    B: "Mang hộp/ly cá nhân",
    C: "Xả rác sau lớp",
    D: "Đốt rác",
    ans: "B",
  },
  {
    id: "E58",
    level: "E",
    q: "Khi bị kẹt do ngập, nên:",
    A: "Đi vào chỗ nước chảy xiết",
    B: "Gọi người lớn/cứu hộ và ở nơi cao",
    C: "Nhảy xuống bơi",
    D: "Đi gần dây điện",
    ans: "B",
  },
  {
    id: "E59",
    level: "E",
    q: "Sử dụng điều hòa hợp lý:",
    A: "Để 16°C",
    B: "Để 26–28°C và đóng kín phòng",
    C: "Mở cửa sổ khi bật",
    D: "Bật khi không có ai",
    ans: "B",
  },
  {
    id: "E60",
    level: "E",
    q: "Mưa đá có thể làm:",
    A: "Vỡ mái tôn, hỏng cây trồng",
    B: "Tăng độ mặn",
    C: "Gây núi lửa",
    D: "Dừng gió",
    ans: "A",
  },

  // ===================== 60 CÂU TRUNG BÌNH (M01–M60) =====================
  {
    id: "M01",
    level: "M",
    q: "Vì sao không nên đi xe máy qua đoạn ngập sâu?",
    A: "Vì dễ bẩn xe",
    B: "Vì có thể bị cuốn + chết máy + hố ga",
    C: "Vì tốn xăng",
    D: "Vì đường dài",
    ans: "B",
  },
  {
    id: "M02",
    level: "M",
    q: "Trong bão, cách an toàn với kính cửa sổ:",
    A: "Đứng sát nhìn ra ngoài",
    B: "Dán băng keo chữ X và tránh gần",
    C: "Đập kính cho khỏi vỡ",
    D: "Mở hé cho đỡ áp lực",
    ans: "B",
  },
  {
    id: "M03",
    level: "M",
    q: "Tại sao trồng rừng ngập mặn giúp chống bão?",
    A: "Làm bão đổi hướng",
    B: "Giảm sóng, giữ đất, giảm xói lở",
    C: "Làm nước mặn hơn",
    D: "Tạo mưa đá",
    ans: "B",
  },
  {
    id: "M04",
    level: "M",
    q: "Hành động nào giảm phát thải CO₂ hiệu quả hơn?",
    A: "Tắt đèn 1 giờ",
    B: "Đi xe đạp/đi bộ thay xe máy quãng ngắn thường xuyên",
    C: "Mua thêm đồ nhựa",
    D: "Đốt rác",
    ans: "B",
  },
  {
    id: "M05",
    level: "M",
    q: "Dấu hiệu cảnh báo lũ quét vùng núi:",
    A: "Nước suối đục, dâng nhanh, có tiếng ầm",
    B: "Gió nhẹ",
    C: "Trời quang",
    D: "Sương mỏng",
    ans: "A",
  },
  {
    id: "M06",
    level: "M",
    q: "Vì sao sau lũ dễ bùng phát bệnh tiêu chảy?",
    A: "Do trời lạnh",
    B: "Do nước bẩn, vi khuẩn lây qua ăn uống",
    C: "Do thiếu internet",
    D: "Do ăn cay",
    ans: "B",
  },
  {
    id: "M07",
    level: "M",
    q: "Phân loại rác đúng là:",
    A: "Pin bỏ chung với vỏ trái cây",
    B: "Rác hữu cơ/nhựa/kim loại/pin tách riêng",
    C: "Tất cả bỏ 1 túi",
    D: "Đốt hết",
    ans: "B",
  },
  {
    id: "M08",
    level: "M",
    q: "Hiệu ứng nhà kính tăng mạnh khi:",
    A: "Tăng khí CO₂, CH₄… trong khí quyển",
    B: "Tăng gió mùa",
    C: "Tăng mưa phùn",
    D: "Tăng cầu vồng",
    ans: "A",
  },
  {
    id: "M09",
    level: "M",
    q: "Nắng nóng đô thị nặng hơn vì:",
    A: "Nhiều cây",
    B: "Hiệu ứng đảo nhiệt: bê tông hấp thụ nhiệt",
    C: "Nhiều sông",
    D: "Nhiều ruộng",
    ans: "B",
  },
  {
    id: "M10",
    level: "M",
    q: "Khi sét đánh gần, dấu hiệu nguy hiểm:",
    A: "Tóc dựng, nghe lách tách",
    B: "Trời xanh",
    C: "Không gió",
    D: "Mưa nhỏ",
    ans: "A",
  },
  {
    id: "M11",
    level: "M",
    q: "Trong bão, ưu tiên sạc dự phòng vì:",
    A: "Để chơi game",
    B: "Để liên lạc khi mất điện",
    C: "Để chụp hình",
    D: "Để bật loa",
    ans: "B",
  },
  {
    id: "M12",
    level: "M",
    q: "Vì sao không nên dùng bếp than trong phòng kín mùa lạnh?",
    A: "Vì nóng",
    B: "Nguy cơ ngộ độc CO (khí không màu)",
    C: "Vì tốn than",
    D: "Vì khói ít",
    ans: "B",
  },
  {
    id: "M13",
    level: "M",
    q: "Một cách giảm nguy cơ sạt lở quanh nhà:",
    A: "Chặt hết cây",
    B: "Trồng cây giữ đất, thoát nước tốt",
    C: "Đổ nước liên tục vào taluy",
    D: "Đào bới chân dốc",
    ans: "B",
  },
  {
    id: "M14",
    level: "M",
    q: "Khi có cảnh báo mưa lớn diện rộng, việc nên làm:",
    A: "Đi câu cá",
    B: "Kiểm tra mái, cống thoát, di chuyển đồ dễ hư lên cao",
    C: "Bỏ mặc",
    D: "Tắt hết thông tin",
    ans: "B",
  },
  {
    id: "M15",
    level: "M",
    q: "Nước biển dâng gây tác động nào ở ĐBSCL?",
    A: "Tăng nước ngọt",
    B: "Xâm nhập mặn, ngập vùng thấp",
    C: "Giảm triều",
    D: "Giảm sóng",
    ans: "B",
  },
  {
    id: "M16",
    level: "M",
    q: "Chỉ số UV cao nghĩa là:",
    A: "Nắng ít",
    B: "Tia UV mạnh, dễ hại da/mắt",
    C: "Trời lạnh",
    D: "Gió yếu",
    ans: "B",
  },
  {
    id: "M17",
    level: "M",
    q: "Nếu phải lội nước, cách giảm rủi ro:",
    A: "Đi chỗ tối",
    B: "Dùng gậy dò, tránh nơi nước xoáy/miệng cống",
    C: "Chạy nhanh",
    D: "Đi sát dây điện",
    ans: "B",
  },
  {
    id: "M18",
    level: "M",
    q: "Vì sao hạn hán có thể làm tăng cháy rừng?",
    A: "Vì nước nhiều",
    B: "Vì thảm thực vật khô dễ bắt lửa",
    C: "Vì gió giảm",
    D: "Vì mưa tăng",
    ans: "B",
  },
  {
    id: "M19",
    level: "M",
    q: "Cách tiết kiệm điện “đúng” với tủ lạnh:",
    A: "Mở ra lâu cho mát",
    B: "Đóng kín, không nhồi quá đầy, chỉnh nhiệt hợp lý",
    C: "Để cửa hở",
    D: "Đặt sát bếp nóng",
    ans: "B",
  },
  {
    id: "M20",
    level: "M",
    q: "Khi có bão, vì sao cần chằng chống mái tôn?",
    A: "Cho đẹp",
    B: "Tránh bị gió lật bay gây tai nạn",
    C: "Vì mưa nhỏ",
    D: "Vì lạnh",
    ans: "B",
  },
  {
    id: "M21",
    level: "M",
    q: "Trong sơ cứu chảy máu, bước đúng là:",
    A: "Rửa bằng nước ao",
    B: "Ép trực tiếp lên vết thương bằng gạc sạch",
    C: "Bôi đất",
    D: "Cào mạnh",
    ans: "B",
  },
  {
    id: "M22",
    level: "M",
    q: "Tại sao không đứng gần bờ sông khi triều cường?",
    A: "Vì muỗi",
    B: "Vì sạt lở bất ngờ, nước dâng nhanh",
    C: "Vì trời tối",
    D: "Vì cá ít",
    ans: "B",
  },
  {
    id: "M23",
    level: "M",
    q: "Khí nào thường được nhắc nhiều trong biến đổi khí hậu?",
    A: "CO₂",
    B: "O₂",
    C: "N₂",
    D: "He",
    ans: "A",
  },
  {
    id: "M24",
    level: "M",
    q: "Một hành động “xanh” trong ăn uống:",
    A: "Lãng phí thức ăn",
    B: "Ăn vừa đủ, hạn chế bỏ thừa",
    C: "Mua nhiều rồi vứt",
    D: "Dùng ly nhựa mỗi bữa",
    ans: "B",
  },
  {
    id: "M25",
    level: "M",
    q: "Vì sao không nên sạc điện thoại khi đang ướt?",
    A: "Vì chậm",
    B: "Nguy cơ chập điện/giật",
    C: "Vì tốn pin",
    D: "Vì nóng",
    ans: "B",
  },
  {
    id: "M26",
    level: "M",
    q: "Khi có nguy cơ bão, nên chuẩn bị giấy tờ:",
    A: "Để ngoài trời cho khô",
    B: "Bỏ vào túi chống nước, mang theo khi sơ tán",
    C: "Xé bỏ",
    D: "Cho bạn giữ ngẫu nhiên",
    ans: "B",
  },
  {
    id: "M27",
    level: "M",
    q: "Vì sao thành phố hay ngập khi mưa lớn?",
    A: "Vì mưa ít",
    B: "Cống tắc + bê tông hóa làm nước khó thấm",
    C: "Vì gió nhẹ",
    D: "Vì trời lạnh",
    ans: "B",
  },
  {
    id: "M28",
    level: "M",
    q: "Dông lốc có thể gây:",
    A: "Tốc mái, gãy cây, đổ cột",
    B: "Nước biển dâng ngay",
    C: "Núi lửa",
    D: "Động đất",
    ans: "A",
  },
  {
    id: "M29",
    level: "M",
    q: "Khi nghe tin giả về thiên tai, cách xử lý tốt:",
    A: "Gây hoang mang",
    B: "Xác minh từ cơ quan khí tượng/chính quyền",
    C: "Chỉ đọc bình luận",
    D: "Tin theo người lạ",
    ans: "B",
  },
  {
    id: "M30",
    level: "M",
    q: "Tại sao cần tránh “điểm thấp” khi bão?",
    A: "Vì mát",
    B: "Vì dễ ngập, nước dâng",
    C: "Vì xa nhà",
    D: "Vì ít sóng",
    ans: "B",
  },
  {
    id: "M31",
    level: "M",
    q: "Lũ ống/lũ quét thường xảy ra ở:",
    A: "Vùng núi dốc, suối nhỏ",
    B: "Sa mạc",
    C: "Biển sâu",
    D: "Đồng bằng khô",
    ans: "A",
  },
  {
    id: "M32",
    level: "M",
    q: "Mưa axit có thể làm:",
    A: "Ăn mòn kim loại, hại cây",
    B: "Tăng cá",
    C: "Tăng đất",
    D: "Tăng tuyết",
    ans: "A",
  },
  {
    id: "M33",
    level: "M",
    q: "Để phòng sốt xuất huyết sau mưa lũ:",
    A: "Để nước đọng",
    B: "Diệt lăng quăng, ngủ màn",
    C: "Đổ rác bừa",
    D: "Uống nước bẩn",
    ans: "B",
  },
  {
    id: "M34",
    level: "M",
    q: "Một cách giảm nguy cơ điện giật mùa mưa:",
    A: "Ổ cắm sát sàn nơi hay ngập",
    B: "Nâng ổ cắm, dùng aptomat chống giật",
    C: "Dùng dây điện trần",
    D: "Cắm quá tải",
    ans: "B",
  },
  {
    id: "M35",
    level: "M",
    q: "Khi có sương mù dày, nguy cơ lớn nhất:",
    A: "Nắng gắt",
    B: "Tai nạn giao thông do tầm nhìn kém",
    C: "Nước biển dâng",
    D: "Động đất",
    ans: "B",
  },
  {
    id: "M36",
    level: "M",
    q: "Biến đổi khí hậu có thể làm mùa mưa:",
    A: "Ổn định y như cũ",
    B: "Thất thường, mưa cực đoan hơn",
    C: "Không bao giờ mưa",
    D: "Chỉ mưa đêm",
    ans: "B",
  },
  {
    id: "M37",
    level: "M",
    q: "Tại sao cần tránh cắm trại ven suối mùa mưa?",
    A: "Vì muỗi",
    B: "Nguy cơ nước dâng nhanh/lũ quét",
    C: "Vì xa chợ",
    D: "Vì lạnh",
    ans: "B",
  },
  {
    id: "M38",
    level: "M",
    q: "Nếu bị kẹt trong nhà khi ngập, ưu tiên:",
    A: "Ra ngoài ngay",
    B: "Lên tầng cao, ngắt điện nếu an toàn, gọi trợ giúp",
    C: "Bật điện mọi phòng",
    D: "Đứng dưới tầng trệt",
    ans: "B",
  },
  {
    id: "M39",
    level: "M",
    q: "Tại sao cần dự trữ nước sạch khi bão?",
    A: "Để rửa xe",
    B: "Có thể mất nước/ô nhiễm nguồn",
    C: "Để tưới cây nhiều",
    D: "Cho vui",
    ans: "B",
  },
  {
    id: "M40",
    level: "M",
    q: "Một cách giảm “đảo nhiệt đô thị”:",
    A: "Tăng bê tông",
    B: "Tăng cây xanh, mái/ tường xanh",
    C: "Đốt rác",
    D: "Bật máy lạnh ngoài trời",
    ans: "B",
  },
  {
    id: "M41",
    level: "M",
    q: "Lời khuyên khi có cảnh báo sạt lở:",
    A: "Ở lại chân dốc",
    B: "Rời khu vực dốc, khe suối ngay",
    C: "Đào thêm đất",
    D: "Tập trung dưới taluy",
    ans: "B",
  },
  {
    id: "M42",
    level: "M",
    q: "Khi mưa lớn, vì sao không bơi ở sông rạch?",
    A: "Vì nước ấm",
    B: "Dòng chảy mạnh + rác + xoáy nguy hiểm",
    C: "Vì cá ít",
    D: "Vì trời sáng",
    ans: "B",
  },
  {
    id: "M43",
    level: "M",
    q: "Một cách giảm lãng phí thực phẩm:",
    A: "Mua quá tay",
    B: "Lên kế hoạch bữa ăn, bảo quản đúng",
    C: "Bỏ đồ thừa",
    D: "Không phân loại",
    ans: "B",
  },
  {
    id: "M44",
    level: "M",
    q: "Vì sao rừng bị chặt làm tăng lũ?",
    A: "Vì lá nhiều",
    B: "Giảm giữ nước/giữ đất → nước chảy nhanh",
    C: "Vì trời tối",
    D: "Vì gió yếu",
    ans: "B",
  },
  {
    id: "M45",
    level: "M",
    q: "Khi có gió giật mạnh, vị trí trong nhà an toàn hơn:",
    A: "Sát cửa kính",
    B: "Phòng phía trong, tránh cửa sổ",
    C: "Ban công",
    D: "Mái hiên",
    ans: "B",
  },
  {
    id: "M46",
    level: "M",
    q: "Tại sao nước ngập dễ che giấu nguy hiểm?",
    A: "Vì nước trong",
    B: "Vì có hố sâu, vật sắc, nắp cống mất",
    C: "Vì nước mát",
    D: "Vì ít người",
    ans: "B",
  },
  {
    id: "M47",
    level: "M",
    q: "Cách đọc cảnh báo bão: “cấp 10–11” thường nói về:",
    A: "Nhiệt độ",
    B: "Sức gió",
    C: "Độ ẩm",
    D: "Số mây",
    ans: "B",
  },
  {
    id: "M48",
    level: "M",
    q: "Khi xảy ra động đất nhẹ (nếu có), nguyên tắc đúng:",
    A: "Chạy ra ban công",
    B: "Cúi–Che–Giữ (Drop-Cover-Hold)",
    C: "Đứng cạnh cửa kính",
    D: "Chạy xuống cầu thang ngay",
    ans: "B",
  },
  {
    id: "M49",
    level: "M",
    q: "Một cách giảm rác nhựa ở canteen:",
    A: "Đổi sang ly/tô tái sử dụng",
    B: "Thêm ống hút nhựa",
    C: "Gói 2 lớp",
    D: "Bán túi nilon nhiều",
    ans: "A",
  },
  {
    id: "M50",
    level: "M",
    q: "Tại sao cần học sơ cứu cơ bản?",
    A: "Để khoe",
    B: "Giúp xử lý kịp thời khi chờ cứu hộ",
    C: "Để khỏi học",
    D: "Không cần",
    ans: "B",
  },
  {
    id: "M51",
    level: "M",
    q: "Dấu hiệu say nắng/sốc nhiệt:",
    A: "Da lạnh run",
    B: "Chóng mặt, đau đầu, buồn nôn, da nóng",
    C: "Ngứa nhẹ",
    D: "Buồn ngủ do học",
    ans: "B",
  },
  {
    id: "M52",
    level: "M",
    q: "Khi có cảnh báo “mưa rất to”, chuẩn bị đi học nên:",
    A: "Mang áo mưa/đồ chống nước, tránh tuyến ngập",
    B: "Đi đường ngập sâu cho nhanh",
    C: "Bỏ giày xuống nước",
    D: "Đi sát kênh",
    ans: "A",
  },
  {
    id: "M53",
    level: "M",
    q: "Vì sao pin/ắc quy bỏ bừa gây hại?",
    A: "Vì nặng",
    B: "Rò hóa chất, ô nhiễm đất nước",
    C: "Vì nóng",
    D: "Vì rẻ",
    ans: "B",
  },
  {
    id: "M54",
    level: "M",
    q: "Một hành động giảm phát thải ở nhà:",
    A: "Giặt đồ ít lần, gom đủ mẻ",
    B: "Bật máy giặt 1 áo",
    C: "Bật nước nóng lâu",
    D: "Mở cửa tủ lạnh cho mát",
    ans: "A",
  },
  {
    id: "M55",
    level: "M",
    q: "Khi bão tới, vì sao cần cắt tỉa cành cây gần nhà?",
    A: "Cho đẹp",
    B: "Giảm gãy đổ gây nguy hiểm",
    C: "Vì cây không cần",
    D: "Vì lá rụng ít",
    ans: "B",
  },
  {
    id: "M56",
    level: "M",
    q: "Xâm nhập mặn là:",
    A: "Nước ngọt thành nước đá",
    B: "Nước mặn lấn vào sông/kênh nội đồng",
    C: "Nước mưa tăng",
    D: "Gió đổi",
    ans: "B",
  },
  {
    id: "M57",
    level: "M",
    q: "Khi sét đánh vào đường dây điện, nguy cơ là:",
    A: "Mất sóng wifi",
    B: "Quá áp, cháy thiết bị điện",
    C: "Tăng pin",
    D: "Tăng âm thanh",
    ans: "B",
  },
  {
    id: "M58",
    level: "M",
    q: "Khi mưa lớn, lý do không nên đứng dưới mái tôn hở:",
    A: "Vì mưa nhỏ",
    B: "Dễ bị điện giật nếu rò điện",
    C: "Vì lạnh",
    D: "Vì tối",
    ans: "B",
  },
  {
    id: "M59",
    level: "M",
    q: "Trong lũ, nước có thể nhiễm:",
    A: "Nước hoa",
    B: "Vi khuẩn, hóa chất, rác thải",
    C: "Vitamin",
    D: "Đường",
    ans: "B",
  },
  {
    id: "M60",
    level: "M",
    q: "Biện pháp giảm thiệt hại bão cho nhà:",
    A: "Không gia cố gì",
    B: "Gia cố mái, cửa, dọn vật dễ bay",
    C: "Để đồ nhẹ ngoài sân",
    D: "Mở cửa cho gió vào",
    ans: "B",
  },

  // ===================== 60 CÂU KHÓ (H01–H60) =====================
  {
    id: "H01",
    level: "H",
    q: "Vì sao khí methane (CH₄) được xem là khí nhà kính mạnh?",
    A: "Vì không hấp thụ nhiệt",
    B: "Vì khả năng giữ nhiệt cao hơn CO₂ trong thời gian nhất định",
    C: "Vì biến thành O₂",
    D: "Vì làm lạnh Trái Đất",
    ans: "B",
  },
  {
    id: "H02",
    level: "H",
    q: "Hiện tượng El Niño thường liên quan đến:",
    A: "Giảm nhiệt toàn cầu ngay",
    B: "Biến đổi nhiệt độ mặt nước Thái Bình Dương làm thời tiết cực đoan",
    C: "Chỉ gây tuyết",
    D: "Chỉ gây động đất",
    ans: "B",
  },
  {
    id: "H03",
    level: "H",
    q: "Vì sao đô thị hóa làm tăng ngập?",
    A: "Tăng thấm nước",
    B: "Giảm bề mặt thấm, tăng dòng chảy mặt nhanh",
    C: "Giảm mưa",
    D: "Tăng đất rừng",
    ans: "B",
  },
  {
    id: "H04",
    level: "H",
    q: "Khi nhiệt độ tăng, không khí giữ ẩm nhiều hơn dẫn đến:",
    A: "Mưa cực đoan tăng",
    B: "Mưa giảm mãi",
    C: "Không có bão",
    D: "Gió ngừng",
    ans: "A",
  },
  {
    id: "H05",
    level: "H",
    q: "Nước biển dâng do 2 nguyên nhân chính:",
    A: "Sóng to + thủy triều",
    B: "Băng tan + giãn nở nhiệt của nước biển",
    C: "Mưa nhiều + gió",
    D: "Động đất + núi lửa",
    ans: "B",
  },
  {
    id: "H06",
    level: "H",
    q: "Vì sao rừng ngập mặn giảm xói lở?",
    A: "Tạo sóng lớn",
    B: "Rễ giữ bùn cát và làm giảm năng lượng sóng",
    C: "Tăng độ mặn",
    D: "Làm gió mạnh",
    ans: "B",
  },
  {
    id: "H07",
    level: "H",
    q: "Kịch bản xấu khi xâm nhập mặn kéo dài ở ĐBSCL:",
    A: "Tăng nước ngọt",
    B: "Thiếu nước tưới, giảm năng suất, thiếu nước sinh hoạt",
    C: "Tăng cá nước ngọt",
    D: "Tăng rừng tự nhiên",
    ans: "B",
  },
  {
    id: "H08",
    level: "H",
    q: "Tại sao cảnh báo sớm (early warning) cứu được nhiều người?",
    A: "Vì làm bão yếu đi",
    B: "Cho thời gian sơ tán/chuẩn bị trước khi rủi ro xảy ra",
    C: "Vì làm mưa tạnh",
    D: "Vì tăng điện",
    ans: "B",
  },
  {
    id: "H09",
    level: "H",
    q: "“Thích ứng” với BĐKH khác “giảm nhẹ” ở chỗ:",
    A: "Giống nhau",
    B: "Thích ứng: giảm tác hại; Giảm nhẹ: giảm nguyên nhân phát thải",
    C: "Thích ứng: tăng phát thải",
    D: "Giảm nhẹ: không liên quan",
    ans: "B",
  },
  {
    id: "H10",
    level: "H",
    q: "Vì sao sau bão dễ có dịch bệnh đường ruột?",
    A: "Vì thiếu mạng",
    B: "Nước sạch bị nhiễm bẩn, vệ sinh kém, thực phẩm hỏng",
    C: "Vì học nhiều",
    D: "Vì lạnh",
    ans: "B",
  },
  {
    id: "H11",
    level: "H",
    q: "Rủi ro lớn khi bơi gần cống thoát nước mùa mưa:",
    A: "Nước trong",
    B: "Xoáy hút + chênh áp + rác cuốn",
    C: "Cá nhiều",
    D: "Nước mát",
    ans: "B",
  },
  {
    id: "H12",
    level: "H",
    q: "Khi bão đổ bộ, vùng nào thường chịu gió mạnh hơn?",
    A: "Phía trong mắt bão",
    B: "Vùng ven biển gần tâm bão và dải gió mạnh",
    C: "Vùng núi xa",
    D: "Sa mạc",
    ans: "B",
  },
  {
    id: "H13",
    level: "H",
    q: "Giải pháp “tự nhiên” giảm ngập đô thị:",
    A: "Bê tông hóa toàn bộ",
    B: "Hồ điều hòa + công viên thấm nước + cây xanh",
    C: "Lấp kênh rạch",
    D: "Chặn cống",
    ans: "B",
  },
  {
    id: "H14",
    level: "H",
    q: "Vì sao sóng nhiệt nguy hiểm hơn khi độ ẩm cao?",
    A: "Vì mồ hôi bay hơi kém, cơ thể khó hạ nhiệt",
    B: "Vì gió mạnh",
    C: "Vì trời tối",
    D: "Vì lạnh",
    ans: "A",
  },
  {
    id: "H15",
    level: "H",
    q: "Tại sao cháy rừng làm biến đổi khí hậu nặng hơn?",
    A: "Vì tạo mưa",
    B: "Thải CO₂ + mất khả năng hấp thụ CO₂ của rừng",
    C: "Vì tăng cây",
    D: "Vì giảm khói",
    ans: "B",
  },
  {
    id: "H16",
    level: "H",
    q: "Trong quản lý rủi ro thiên tai, “tổn thương” nghĩa là:",
    A: "Sức gió",
    B: "Mức dễ bị ảnh hưởng của người/tài sản",
    C: "Nhiệt độ",
    D: "Độ ẩm",
    ans: "B",
  },
  {
    id: "H17",
    level: "H",
    q: "Điều nào làm tăng nguy cơ lũ quét ở lưu vực?",
    A: "Giữ rừng",
    B: "Mất rừng + mưa lớn + địa hình dốc",
    C: "Trồng cây",
    D: "Có hồ điều tiết",
    ans: "B",
  },
  {
    id: "H18",
    level: "H",
    q: "Vì sao cần bản đồ nguy cơ (ngập/sạt lở)?",
    A: "Cho vui",
    B: "Giúp quy hoạch và sơ tán đúng điểm an toàn",
    C: "Để tăng giá đất",
    D: "Để quảng cáo",
    ans: "B",
  },
  {
    id: "H19",
    level: "H",
    q: "“Phát thải ròng bằng 0 (net zero)” nghĩa là:",
    A: "Không phát thải gì",
    B: "Phát thải còn lại được hấp thụ/bù trừ tương đương",
    C: "Chỉ trồng cây",
    D: "Chỉ tắt điện",
    ans: "B",
  },
  {
    id: "H20",
    level: "H",
    q: "Vì sao mực nước biển dâng có thể làm sạt lở bờ biển tăng?",
    A: "Vì sóng nhỏ",
    B: "Sóng/triều tác động sâu hơn vào bờ, xói mòn mạnh",
    C: "Vì đất tự mọc",
    D: "Vì gió giảm",
    ans: "B",
  },
  {
    id: "H21",
    level: "H",
    q: "Khi mưa cực đoan tăng, hệ thống thoát nước đô thị cần:",
    A: "Giảm kích thước cống",
    B: "Nâng cấp công suất + giải pháp thấm/giữ nước",
    C: "Bịt miệng cống",
    D: "Lấp kênh",
    ans: "B",
  },
  {
    id: "H22",
    level: "H",
    q: "Tại sao hạn hán kéo dài ảnh hưởng an ninh lương thực?",
    A: "Vì mưa tăng",
    B: "Thiếu nước tưới, giảm sản lượng, tăng giá",
    C: "Vì gió mạnh",
    D: "Vì lạnh",
    ans: "B",
  },
  {
    id: "H23",
    level: "H",
    q: "“Xói lở” khác “sạt lở” ở chỗ:",
    A: "Giống hệt",
    B: "Xói lở: mòn dần do nước/sóng; Sạt lở: khối đất đá trượt đổ",
    C: "Sạt lở: mòn dần",
    D: "Xói lở: trượt đổ",
    ans: "B",
  },
  {
    id: "H24",
    level: "H",
    q: "Biện pháp giảm rủi ro cho trường học vùng bão:",
    A: "Không tập huấn",
    B: "Kế hoạch sơ tán + gia cố công trình + diễn tập định kỳ",
    C: "Chỉ dán khẩu hiệu",
    D: "Chỉ mua quạt",
    ans: "B",
  },
  {
    id: "H25",
    level: "H",
    q: "Vì sao thông tin thiên tai cần “một nguồn chính thống”?",
    A: "Vì dễ share",
    B: "Tránh hoang mang, sai lệch gây nguy hiểm khi sơ tán",
    C: "Vì cho vui",
    D: "Vì rẻ",
    ans: "B",
  },
  {
    id: "H26",
    level: "H",
    q: "Khi nhiệt độ tăng, nguy cơ bệnh do muỗi tăng vì:",
    A: "Muỗi chết hết",
    B: "Muỗi sinh sản nhanh, phạm vi sống mở rộng",
    C: "Muỗi thành cá",
    D: "Muỗi ngủ đông",
    ans: "B",
  },
  {
    id: "H27",
    level: "H",
    q: "Trong bão, vì sao nên tránh dùng điện khi nhà bị ngập?",
    A: "Vì mất wifi",
    B: "Nguy cơ rò điện gây giật chết người",
    C: "Vì tốn tiền",
    D: "Vì nóng",
    ans: "B",
  },
  {
    id: "H28",
    level: "H",
    q: "Giải pháp nông nghiệp thích ứng mặn:",
    A: "Cố trồng lúa mọi nơi",
    B: "Chuyển đổi cây/con phù hợp, tưới tiết kiệm",
    C: "Đổ thêm muối",
    D: "Bỏ đất hoang",
    ans: "B",
  },
  {
    id: "H29",
    level: "H",
    q: "“Tái sử dụng” khác “tái chế” ở chỗ:",
    A: "Giống nhau",
    B: "Tái sử dụng: dùng lại; Tái chế: xử lý thành vật liệu mới",
    C: "Tái chế: dùng lại",
    D: "Không khác",
    ans: "B",
  },
  {
    id: "H30",
    level: "H",
    q: "Vì sao cần “diễn tập” phòng chống thiên tai?",
    A: "Cho vui",
    B: "Tạo phản xạ, giảm hoảng loạn khi thật sự xảy ra",
    C: "Để nghỉ học",
    D: "Để quay clip",
    ans: "B",
  },
  {
    id: "H31",
    level: "H",
    q: "Khi sạt lở có thể tiếp diễn, quy tắc an toàn:",
    A: "Đứng xem",
    B: "Rời xa, không quay lại lấy đồ, chờ thông báo",
    C: "Chạy lại chụp hình",
    D: "Đào đất xem",
    ans: "B",
  },
  {
    id: "H32",
    level: "H",
    q: "Vì sao “giữ đất trống” sau chặt rừng tăng lũ?",
    A: "Vì nước thấm nhiều",
    B: "Vì đất bị rửa trôi, giảm thấm, tăng dòng chảy",
    C: "Vì mưa giảm",
    D: "Vì gió giảm",
    ans: "B",
  },
  {
    id: "H33",
    level: "H",
    q: "Khi bão mạnh, vì sao cửa ra vào cần gia cố?",
    A: "Vì đẹp",
    B: "Áp lực gió làm bung cửa, gió lùa phá hỏng nhà",
    C: "Vì lạnh",
    D: "Vì tối",
    ans: "B",
  },
  {
    id: "H34",
    level: "H",
    q: "Một chỉ báo khí hậu dài hạn là:",
    A: "Nhiệt độ trung bình nhiều năm",
    B: "Mưa hôm nay",
    C: "Gió lúc này",
    D: "Mây giờ",
    ans: "A",
  },
  {
    id: "H35",
    level: "H",
    q: "Giải pháp giảm phát thải trong giao thông:",
    A: "Tăng xe cá nhân",
    B: "Phát triển xe buýt/đi chung/xe điện + đi bộ",
    C: "Đốt rác",
    D: "Bật máy nổ chờ",
    ans: "B",
  },
  {
    id: "H36",
    level: "H",
    q: "Vì sao thiếu nước sạch sau lũ là nguy cơ lớn?",
    A: "Vì không tắm",
    B: "Tăng bệnh truyền qua nước + khó vệ sinh",
    C: "Vì nóng",
    D: "Vì lạnh",
    ans: "B",
  },
  {
    id: "H37",
    level: "H",
    q: "Khi bão vào, “mắt bão” thường có:",
    A: "Gió mạnh nhất",
    B: "Gió lặng tạm thời nhưng nguy hiểm vì gió sẽ đổi chiều mạnh lại",
    C: "Tuyết rơi",
    D: "Động đất",
    ans: "B",
  },
  {
    id: "H38",
    level: "H",
    q: "Tại sao cần chừa hành lang thoát lũ sông rạch?",
    A: "Để xây nhà sát bờ",
    B: "Để nước có chỗ thoát, giảm ngập và xói lở",
    C: "Để bán đất",
    D: "Để câu cá",
    ans: "B",
  },
  {
    id: "H39",
    level: "H",
    q: "Trong quản lý rủi ro, “phơi bày” nghĩa là:",
    A: "Số người/tài sản nằm trong vùng nguy hiểm",
    B: "Sức gió",
    C: "Nhiệt độ",
    D: "Độ ẩm",
    ans: "A",
  },
  {
    id: "H40",
    level: "H",
    q: "Vì sao tiết kiệm năng lượng là “giảm nhẹ” BĐKH?",
    A: "Vì làm mưa",
    B: "Giảm nhu cầu điện → giảm đốt nhiên liệu hóa thạch",
    C: "Vì tăng gió",
    D: "Vì tăng sóng",
    ans: "B",
  },
  {
    id: "H41",
    level: "H",
    q: "Khi triều cường + mưa lớn trùng nhau:",
    A: "Ngập có thể nặng hơn do thoát nước kém",
    B: "Ngập giảm",
    C: "Không ảnh hưởng",
    D: "Chỉ có gió",
    ans: "A",
  },
  {
    id: "H42",
    level: "H",
    q: "Một ví dụ “thích ứng” ở trường học:",
    A: "Trồng thêm cây và làm mái che chống nóng",
    B: "Đốt rác",
    C: "Bật điện cả ngày",
    D: "Tăng nhựa 1 lần",
    ans: "A",
  },
  {
    id: "H43",
    level: "H",
    q: "Vì sao lũ ở hạ lưu có thể tăng khi thượng nguồn mưa lớn?",
    A: "Vì nước chảy về, cộng dồn lưu lượng",
    B: "Vì nước biến mất",
    C: "Vì gió đổi",
    D: "Vì lạnh",
    ans: "A",
  },
  {
    id: "H44",
    level: "H",
    q: "Biện pháp giảm rủi ro điện khi bão:",
    A: "Dùng ổ cắm rẻ hở",
    B: "Aptomat/CB, ổ cao, dây điện đạt chuẩn",
    C: "Dây trần",
    D: "Cắm quá tải",
    ans: "B",
  },
  {
    id: "H45",
    level: "H",
    q: "Tại sao “xanh hóa” mái nhà giúp giảm nhiệt?",
    A: "Vì làm nhà nặng",
    B: "Tăng che phủ, bốc hơi làm mát, giảm hấp thụ nhiệt",
    C: "Vì tăng khói",
    D: "Vì tăng bê tông",
    ans: "B",
  },
  {
    id: "H46",
    level: "H",
    q: "Trong lũ, nước đục chảy nhanh thường nguy hiểm hơn vì:",
    A: "Dễ uống",
    B: "Che vật cản + lực nước lớn + khó ước lượng độ sâu",
    C: "Vì mát",
    D: "Vì sạch",
    ans: "B",
  },
  {
    id: "H47",
    level: "H",
    q: "Tại sao phải ưu tiên nhóm dễ tổn thương khi sơ tán?",
    A: "Vì họ chậm hơn/khó tự bảo vệ (trẻ nhỏ, người già…)",
    B: "Vì họ gây bão",
    C: "Vì họ không cần",
    D: "Vì cho vui",
    ans: "A",
  },
  {
    id: "H48",
    level: "H",
    q: "Khái niệm “dấu chân carbon” là:",
    A: "Vết chân ngoài sân",
    B: "Tổng phát thải khí nhà kính do một người/sản phẩm tạo ra",
    C: "Mùi khói",
    D: "Độ ẩm",
    ans: "B",
  },
  {
    id: "H49",
    level: "H",
    q: "Vì sao cần bảo tồn đất ngập nước?",
    A: "Vì ít giá trị",
    B: "Giữ nước, giảm lũ, lọc nước, đa dạng sinh học",
    C: "Vì tạo bão",
    D: "Vì tăng nhựa",
    ans: "B",
  },
  {
    id: "H50",
    level: "H",
    q: "Khi có cháy, khói độc nguy hiểm vì:",
    A: "Nhìn đẹp",
    B: "Gây ngạt, giảm oxy, có khí độc",
    C: "Làm lạnh",
    D: "Tăng vitamin",
    ans: "B",
  },
  {
    id: "H51",
    level: "H",
    q: "Trong bão, gió giật có thể mạnh hơn gió trung bình vì:",
    A: "Do dao động/turbulence và địa hình",
    B: "Do mưa ngừng",
    C: "Do trời sáng",
    D: "Do biển lặng",
    ans: "A",
  },
  {
    id: "H52",
    level: "H",
    q: "Một cách giảm ngập cục bộ ở khu dân cư:",
    A: "Lấp mương",
    B: "Tăng bề mặt thấm + thu gom rác + nạo vét cống",
    C: "Đổ bê tông hết",
    D: "Bịt miệng cống",
    ans: "B",
  },
  {
    id: "H53",
    level: "H",
    q: "Tại sao nuôi trồng thủy sản có thể bị ảnh hưởng bởi BĐKH?",
    A: "Không liên quan",
    B: "Nhiệt độ nước, độ mặn thay đổi làm dịch bệnh/tăng chết",
    C: "Vì wifi yếu",
    D: "Vì cá thích lạnh",
    ans: "B",
  },
  {
    id: "H54",
    level: "H",
    q: "Nếu phải ở lại khi bão mạnh (không kịp sơ tán), ưu tiên vị trí:",
    A: "Phòng có nhiều kính",
    B: "Phòng trong nhà, thấp hơn mái, tránh cửa sổ",
    C: "Ban công",
    D: "Mái nhà",
    ans: "B",
  },
  {
    id: "H55",
    level: "H",
    q: "Sự khác nhau giữa “thời tiết” và “khí hậu” là:",
    A: "Không khác",
    B: "Thời tiết: ngắn hạn; Khí hậu: trung bình dài hạn nhiều năm",
    C: "Khí hậu: hôm nay",
    D: "Thời tiết: 30 năm",
    ans: "B",
  },
  {
    id: "H56",
    level: "H",
    q: "Tại sao cần “đa dạng nguồn nước” khi hạn?",
    A: "Cho vui",
    B: "Giảm phụ thuộc một nguồn dễ cạn/nhiễm mặn",
    C: "Để tốn tiền",
    D: "Để tăng lãng phí",
    ans: "B",
  },
  {
    id: "H57",
    level: "H",
    q: "Biện pháp học đường giảm phát thải:",
    A: "Tắt quạt khi nóng",
    B: "Điện mặt trời mái + tiết kiệm điện + trồng cây",
    C: "Đốt rác",
    D: "Mở điều hòa 16°C",
    ans: "B",
  },
  {
    id: "H58",
    level: "H",
    q: "Vì sao xây nhà sát mép sông tăng rủi ro?",
    A: "Vì đẹp",
    B: "Tăng phơi bày trước sạt lở/xói lở và ngập",
    C: "Vì gần chợ",
    D: "Vì mát",
    ans: "B",
  },
  {
    id: "H59",
    level: "H",
    q: "Một ví dụ “giảm nhẹ” ở gia đình:",
    A: "Trồng cây và giảm dùng điện, phân loại rác",
    B: "Đốt rác nhựa",
    C: "Xả nước thoải mái",
    D: "Bật xe nổ máy chờ",
    ans: "A",
  },
  {
    id: "H60",
    level: "H",
    q: "Vì sao giáo dục rủi ro thiên tai quan trọng cho THCS?",
    A: "Vì khó",
    B: "Tạo kỹ năng tự bảo vệ, lan tỏa thói quen an toàn trong gia đình",
    C: "Vì để thi",
    D: "Vì cho vui",
    ans: "B",
  },
];
